import BackgroundWrapper from "./_components/ui/BackgroundWrapper";
import { Inter, Outfit, Oswald } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes"; 

const inter = Inter({ subsets: ["latin"] });
const outfit = Outfit({ subsets: ["latin"] });
const oswald = Oswald({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <BackgroundWrapper> 
            {children}
          </BackgroundWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
